name: build-artifact

# Only run this when the master branch changes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    #
    # # Install mongodb client
    # - name: Install mongodb
    #   run: sudo apt-get install mongodb

    # Install Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    # Install the python packages (from requirements.txt)
    # cp ./imongo_config.yml ~/.jupyter/imongo_config.yml
    - name: Install python packages
      run: |
        python -m pip install -r requirements_imongo.txt
        pip install git+git://github.com/rtavenar/imongo.git#egg=imongo-kernel --user
        python -m pip install -r requirements.txt

    # Start a local MongoDB server
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0

    # Load databases on the server
    - name: Load databases
      run: |
        cd install_db
        export MONGODB_PORT=27017
        source install_db.sh

    # Build the html version of the book
    - name: Build the html-book
      run: |
        echo "DBQuery.prototype._prettyShell = true" > ~/.mongorc.js
        jupyter-book build .
        tar -cvf mongo_book.tar.gz _build

    # Upload the generated artifact to GitHub
    - name: Upload artifact
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/upload-artifact@v2
      with:
        name: mongo_book
        path: mongo_book.tar.gz

    # Push the book's HTML to github-pages
    - name: Push to gh_pages
      if: ${{ github.event_name == 'push' && main }}
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
